name: Manage EC2 Instances

on:
  schedule:
    - cron: '0 18 * * *' # Runs every day at 6 PM UTC
    - cron: '0 9 * * *'  # Runs every day at 9 AM UTC
  workflow_dispatch: {}

jobs:
  manage-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Execute EC2 management script
        run: |
          chmod +x .github/scripts/manage_ec2_instances.sh
          .github/scripts/manage_ec2_instances.sh
